# general
seed: 42
workers: 1
dataset_dir: "../datasets"

# train options
batch_size: 128
image_size: 128

# model options
resnet: "ResNet34" #ResNet34 / ResNet50
feature_dim: 128

# loss options
learning_rate: 0.00001 #ImageNet 0.00001 CIFAR 0.00001
weight_decay: 0.
instance_temperature: 1.0
cluster_temperature: 2.0

start_epoch: 0
epochs: 500
reload: False
retrain: True

dataset: "CIFAR-100" # CIFAR-10 / CIFAR-100 / ImageNet-10 
model_path: "save/CIFAR100"
label_strategy: 1 # 0-default; 1-personalized
extend_proportion: 0  

i_query_strategy: 0 #0:random 1:diversity
query_strategy: 1 #0:random 1:mix

batch_iquery_num: 0  #initial query num  pair/batch
query_num: 10000 #total query num